apiVersion: apps/v1
kind: Deployment
metadata:
  name: fortunecookie-5b6d965c9c-96l64
spec:
  selector:
    matchLabels:
      app: fortunecookie
  replicas: 3
  template:
    metadata:
      labels:
        app: fortunecookie
    spec:
      containers:
        - name: fortunecookie
          image: srlopes/fortunecookie:v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
